### ISSUE TITLE
Panic when converting cloudposse/terraform-aws-components/modules/vpc

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-converter-terraform#15]
I get a panic when trying to convert https://github.com/cloudposse/terraform-aws-components/tree/main/modules/vpc. This is at commitish 1b338fe664e5debc5bbac30cfe42003f7458575a in case that matters.

Presumably this part is the root cause: "panic: Got argument 2 to join."

Here is the full panic:

```
pulumi convert --from terraform --language python --out ./pulumi
Converting from terraform...
panic: Got argument 2 to join

goroutine 54 [running]:

github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.convertFunctionCallExpr(0x30?, 0xc000098900?, {0xc0010848d0?, 0x0?}, 0xc001078d20)

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.2-0.20230613134813-d9a243d1ef36/pkg/tf2pulumi/convert/tf.go:758 +0xd34

github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.convertExpression(0xc0002261d8?, 0x0?, {0x0?, 0x25?}, {0x3238a30?, 0xc001078d20?})

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.2-0.20230613134813-d9a243d1ef36/pkg/tf2pulumi/convert/tf.go:1372 +0xad

github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.convertOutput(0x29d3ae0?, 0xc000065000, 0xc0006f3c30)

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.2-0.20230613134813-d9a243d1ef36/pkg/tf2pulumi/convert/tf.go:2102 +0x3e8

github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.translateModuleSourceCode(0x0?, {0x3244200, 0xc000ca1c60}, {0x3214af8, 0x1}, {0x3244200?, 0xc0004b4e40?}, {0xc0001d2120, 0xc}, {0x321f4c0, ...})

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.2-0.20230613134813-d9a243d1ef36/pkg/tf2pulumi/convert/tf.go:2733 +0x3ec5

github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.translateRemoteModule(0xc000f5c8f0?, {0xc000058fc0, 0x40}, {0x0, 0x0}, {0x3244200, 0xc0004b4e40}, {0xc0001d2120, 0xc}, {0x321f4c0, ...})

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.2-0.20230613134813-d9a243d1ef36/pkg/tf2pulumi/convert/tf.go:2225 +0x557

github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.translateModuleSourceCode(0xc0006e34b8?, {0x3244280, 0x42cc2e8}, {0xc0004b28a0, 0x57}, {0x3244200?, 0xc0004b4e40?}, {0x3214af8, 0x1}, {0x321f4c0, ...})

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.2-0.20230613134813-d9a243d1ef36/pkg/tf2pulumi/convert/tf.go:2548 +0x6447

github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.TranslateModule(...)

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.2-0.20230613134813-d9a243d1ef36/pkg/tf2pulumi/convert/tf.go:2808

main.(*tfConverter).ConvertProgram(0xc000b40000, {0xc000deb200?, 0x0?}, 0xc000deb230)

	/Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/cmd/pulumi-converter-terraform/main.go:57 +0x24b

github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*converterServer).ConvertProgram(0xc000d8ab20, {0x3237fb0, 0xc000deb200}, 0xc000220ae0)

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.70.1-0.20230611235120-feb5153187d1/go/common/resource/plugin/converter_server.go:64 +0xf7

github.com/pulumi/pulumi/sdk/v3/proto/go._Converter_ConvertProgram_Handler.func1({0x3237fb0, 0xc000deb200}, {0x2bcc1a0?, 0xc000220ae0})

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.70.1-0.20230611235120-feb5153187d1/proto/go/converter_grpc.pb.go:122 +0x78

github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x3237fb0, 0xc000deaea0}, {0x2bcc1a0, 0xc000220ae0}, 0xc0004b4440, 0xc00044e6a8)

	/Users/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3e8

github.com/pulumi/pulumi/sdk/v3/proto/go._Converter_ConvertProgram_Handler({0x2a74660?, 0xc000d8ab20}, {0x3237fb0, 0xc000deaea0}, 0xc00033e230, 0xc000d8aa20)

	/Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.70.1-0.20230611235120-feb5153187d1/proto/go/converter_grpc.pb.go:124 +0x138

google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006ac1e0, {0x3241da0, 0xc000883a00}, 0xc000d10120, 0xc000490b40, 0x425a7f8, 0x0)

	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1337 +0xdf3

google.golang.org/grpc.(*Server).handleStream(0xc0006ac1e0, {0x3241da0, 0xc000883a00}, 0xc000d10120, 0x0)

	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1714 +0xa36

google.golang.org/grpc.(*Server).serveStreams.func1.1()

	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:959 +0x98

created by google.golang.org/grpc.(*Server).serveStreams.func1

	/Users/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:957 +0x18c

error: rpc error: code = Unavailable desc = error reading from server: EOF

```

As an aside, shouldn't plugins crashing with panic trigger the same "please file a bug" panic handler we have in the CLI?

**Comment by Frassle** [comment]
I've just pushed 1.0.4 of the converter out which should fix this panic, but there's still a lot of warnings from this example.

**Comment by justinvp** [comment]
Closing this since the panic has been addressed. https://github.com/pulumi/pulumi/issues/13475 tracks using the "please file a bug" panic handler when plugins abnormally exit.
